#!/bin/bash

EXE=./roborobo
TEMPLATE=config/templateOdneatIrace.properties
FIXED_PARAMS="-l"

OPTIND=1         # Reset in case getopts has been used previously in the shell.

# Initialize our own variables:
m=0.0
n=0.0
w=0.0
t=0.0
e=0.0
l=0.0
x=0.0
r=0.0
s=0.0
i=""
cand=""
#Read the given parameters
while getopts "i:m:w:t:e:n:l:x:r:g:s:c:" opt; do
    case "$opt" in
	m) m=$OPTARG
	    ;;
	w) w=$OPTARG
	    ;;
	t) t=$OPTARG
	    ;;
	e) e=$OPTARG
	    ;;
	n) e=$OPTARG
	    ;;
	l) l=$OPTARG
	    ;;
	x) x=$OPTARG
	    ;;
	r) r=$OPTARG
	    ;;
	s) s=$OPTARG
	    ;;
	i) i=$OPTARG
	    ;;
	c) cand=$OPTARG
	    ;;
    esac

done

#Create parameter file from template
PARAMFNAME="${i}.${cand}.param"

cp ${TEMPLATE} ${PARAMFNAME}

#Read current instance (random seed)
seed=`cat $i`

#For debug
#if [ ! -f debug.log ]; then
#    touch debug.log
#fi
#echo "$i " >> debug.log

#Fill the corresponding parameters
echo -e "\n\n\n#Random Seed for this instance" >> $PARAMFNAME
echo "gRandomSeed = $seed" >> $PARAMFNAME

echo -e "\n\n\n#Parameters being tuned" >> $PARAMFNAME
echo "mutate_only_prob = $m " >> $PARAMFNAME
echo "mutate_link_weights_prob = $w " >> $PARAMFNAME
echo "mutate_toggle_enable_prob = $t " >> $PARAMFNAME
echo "mutate_gene_reenable_prob = $e " >> $PARAMFNAME
echo "mutate_add_node_prob = $n " >> $PARAMFNAME
echo "mutate_add_link_prob = $l " >> $PARAMFNAME
echo "mate_only_prob = $x " >> $PARAMFNAME
echo "recur_only_prob = $r "	 >> $PARAMFNAME
echo "gSigmaRef = $s " >> $PARAMFNAME

if [ ! -f logs/out.log ]; then
   touch logs/out.log
fi

$EXE $FIXED_PARAMS $PARAMFNAME >> logs/out.log 2> /dev/null

timeBack=0.08


#Read "cost/quality" measure of the run (to be minimized)
#Testing with average accumulated swarm fitness (for last 8% of evo)
#Since this measure is to be minimized, we take 1/(avgAccumSwarmFit)
cost=`R --slave --args logs/evolution.log $timeBack < tools/accumMeanEnd.r` #recover it with val=`... `

rm logs/out.log
rm logs/evolution.log

#Acc. swarm fitness is a performance measure to be maximized
#Since irace expects a cost measure to be minimized, -1 times the value is returned
#TOCHECK it could be 1/value
echo  -$cost

