mutate_only_prob 1.0
mutate_link_weights_prob 1.0
mutate_toggle_enable_prob 0.0
mutate_gene_reenable_prob 0.0
mutate_add_node_prob 0.50
mutate_add_link_prob 0.50
mate_multipoint_prob 0.6
mate_only_prob 0.2
recur_only_prob 1.0
newstructure_tries 20